### ISSUE TITLE
NativeModules.RNAlbumsModule.getImageList is not a function

### ISSUE THREAD

**Issue by kytwb** [shimohq/react-native-albums#5]
Can't call `getImageList`; `getAlbumList` works like a charm.

**Comment by kytwb** [comment]
@magicismight any ideas?

**Comment by uditalias** [comment]
@kytwb maybe because its not implemented?

**Comment by kytwb** [comment]
@uditalias Yeah, I noticed later on and forgot to update in here. It's only implemented on Android.
Related: https://github.com/facebook/react-native/issues/10666#issuecomment-365199379
